# Generated by Django 4.0.2 on 2022-03-14 02:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_cuisine_room_host_message_room_cuisine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Recipe',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='recipe',
        ),
    ]
